
name: Update chart data

on:
#   schedule:
#     - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: download-extractor

      - name: Checkout mod database
        uses: actions/checkout@v3
        with:
          name: Raicuparta/ow-mod-db
          ref: "master"
          fetch-depth: 0
          path: ow-mod-db
          
      - name: Get database log
        run: |
          cd ow-mod-db
          git log -p > ../log.txt
          cd ..
        
      - name: Convert log.txt to json
        run: |
          ./download-extractor/bin/Debug/net6.0/OWModDBDownloadCountExtractor.exe log.txt
          
      - name: Log json result
        id: log-json
        run: echo "::set-output name=mods::$(< ./outpput.json sed ':a;N;$!ba;s/\n/ /g')"
